config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :board, :only => [:index] do    
  end
  resources :user, :only => [] do
    collection do 
      post 'change_color'
      post 'set_color'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board
  @@board = []


  def self.initialize(size = 20)
    (0..(size - 1)).each do |row|
        @@board[row] = []
      (0..(size - 1)).each do |column|
        @@board[row] << Cell.new(row, column, Pallete::DEFAULT_COLOR)
      end
    end
    return @@board
  end


  def self.get_board
    return @@board
  end


  def self.set_value row, column, color, updated_by    
    cell = (@@board[row] || [])[column]
    raise "Invalid cell_value" if cell.blank?
    cell.update_color color, updated_by
  end

end

app/models/board_cell.rb
class Cell

  attr_accessor :row, :column, :color, :updated_by, :updated_at

  def initialize row, column, color
    @row = row
    @column = column
    @color = Pallete::DEFAULT_COLOR
  end


  def update_color color, updated_by
    @color = color
    @updated_by = updated_by
    @updated_at = Time.now
  end

end

app/models/cell.rb
class Cell

  attr_reader :row, :column, :color, :updated_by, :updated_at

  def initialize row, column, color
    @row = row
    @column = column
    @color = Pallete::DEFAULT_COLOR
  end


  def update_color color, updated_by
    @color = color
    @updated_by = updated_by
    @updated_at = Time.now
  end

end

app/models/pallete.rb
class Pallete

  DEFAULT_COLOR = "white"

  @@pallete = {

  }


  def self.set_color color, hexcode
    @@pallete[color] = hexcode
    return @@pallete
  end

  def self.get_hexcode color
    return @@pallete[color]
  end

  def self.get_colors 
    return @@pallete
  end

  def self.validate_color color
    !@@pallete[color].blank?
  end

end

app/models/user.rb
class User

  @@user_session_hash = {}

  attr_reader :session_id, :current_color

  def initialize session_id
    @session_id = session_id
    @current_color = Pallete::DEFAULT_COLOR
  end

  def self.find_user_by_session session_id
    return @@user_session_hash[session_id]
  end


  def self.create_new_user_session 
    session_id = SecureRandom.hex
    @@user_session_hash[session_id] = User.new(session_id)
    return @@user_session_hash[session_id]
  end


  def update_board row, column
    Board.set_value row, column, @current_color, @session_id
  end

  def set_color color
    raise "Invalid color provided" unless Pallete.validate_color color
    @current_color = color
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  skip_before_action :verify_authenticity_token  
  before_action :verify_user

  def verify_user
    user_session = cookies[:user_session]
    unless user_session.nil?
      @current_user = User.find_user_by_session user_session
      return @current_user unless @current_user.nil? 
    end    

    @current_user = User.create_new_user_session
    cookies[:user_session] = @current_user.session_id
  end


  def current_user
    return @current_user
  end

end

app/controllers/board_controller.rb
class BoardController < ApplicationController


  def index
    puts current_user.current_color
    @board = Board.get_board
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def change_color
    current_user.set_color params[:color]
    redirect_to board_index_path
  end


  def set_color
    current_user.update_board params[:row].to_i, params[:column].to_i
    redirect_to board_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board/_board.html.erb
<% board = board || [[]] %>
<table style="width:100%;height:100%" border="1">
<% (0..(size - 1)).each do |row| %>
  <tr>
    <% (0..(size - 1)).each do |column| %>
      <% cell = ((board[row] || [])[column]) || OpenStruct.new; color = cell.color || "white";
      title = "Updated by: #{cell.updated_by} at #{cell.updated_at}" unless cell.updated_by.blank?
      color_code = Pallete.get_hexcode color %>
      <td align="center">        
        <a style="display:block;width:100%;height:100%;background-color: <%= color_code %>" href="#<%=row%>-<%=column%>" class="board-cell" title="<%= title %>">
          <%= row %> X <%= column %>
        </a>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<form id="boardSubmitForm" method="post" action="<%= set_color_user_index_path %>">
  <input type="hidden" name="row" id="boardRow"/>
  <input type="hidden" name="column" id="boardColumn"/>
</form>

<script type="text/javascript">
  var cells =document.getElementsByClassName("board-cell");

  for(var i=0; i< cells.length; i++){
    cells[i].onclick = function() {
    var link = this.href;
    var cellCoordinates = link.split("#")[1];
    var row = cellCoordinates.split("-")[0];
    var column = cellCoordinates.split("-")[1]
    document.getElementById("boardRow").value = row;
    document.getElementById("boardColumn").value = column;
    document.getElementById("boardSubmitForm").submit();
    return false;
  }
  }  
</script>

app/views/board/_pallete.html.erb
<table style="width:100%;height:100%" border="1">
<tr>    
  <% Pallete.get_colors.each do |color, value| %>  
        <td align="center">        
          <a style="display:block;width:100%;height:100%;background-color: <%= value %>" href="#<%= color %>" class="pallete-color">          
          </a>
        </td>      
  <% end %>
</tr>
</table>

<form id="colorSubmitForm" method="post" action="<%= change_color_user_index_path %>">
  
  <input type="hidden" name="color" id="colorInput"/>
</form>

<script type="text/javascript">
  var colors =document.getElementsByClassName("pallete-color");

  for(var i=0; i< colors.length; i++){
    colors[i].onclick = function() {
    var link = this.href;
    color = link.split("#")[1];
    document.getElementById("colorInput").value = color;
    document.getElementById("colorSubmitForm").submit();
    return false;
  }
  }  
</script>

app/views/board/index.html.erb
<div class="container" >
  <div class="board" style="height:720px">
    <%= render partial: "board/board", locals: {:size => 20, board: @board}%>
  </div>
  <div class="pallete" style="height:100px">
    <%= render partial: "board/pallete"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Draw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>